# netlify.toml (at project root)
[build]
  publish = "frontend/dist"

[[redirects]]
  from       = "/api/submit"
  to         = "https://script.google.com/macros/s/AKfycbw-ukzXvkbBRRwZuzNn85Xo817oIYqHsTVpCjVY5IpD_hpqASAizevc-WJAg288psdvZw/exec"
  status     = 200
  force      = true
  conditions = { Method = ["POST","OPTIONS"] }

[[redirects]]
  from       = "/*"
  to         = "/index.html"
  status     = 200
  force      = true
  conditions = { Method = ["GET","POST","OPTIONS"] }
