[build]
  publish = "dist"

[[redirects]]
  from       = "/api/submit"
  to         = "https://script.google.com/macros/s/AKfycbw-ukzXvkbBRRwZuzNn85Xo817oIYqHsTVpCjVY5IpD_hpqASAizevc-WJAg288psdvZw/exec"
  status     = 200
  force      = true
  conditions = { Method = ["POST","OPTIONS"] }
